### ISSUE TITLE
Empty Create React App - Metaport Not Working

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/metaport#39]
**Describe the bug**
To test S2S I ran Create React App. From there I installed Metaport. As soon as metaport is added to the page, nothing in the application renders. 

**To Reproduce**
1. ```npx create-react-app [app name]```
2. ```npm install --save @skalenetwork/metaport```
3. Removed everything but App.js, index.js, and index.css
4. App.js is ```
import { Metaport } from '@skalenetwork/metaport';

const widget = new Metaport({
  open: true,
  network: 'staging',
  chains: ['mainnet', 'chainName1'],
  tokens: {'mainnet': {'eth': {}}}
});

function App() {

  return (
    <div style={{width: '50vh', height: '50vh', backgroundColor: 'pink'}}>
      /// I put the <h1\> on purpose to avoid MD formatting issues
      <h1\>Metaport React Test</h1>
      <div id='metaport'></div>  
    </div>
  );
}

export default App;

`
5. Package.json is 

`{
  "name": "metaport-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@skalenetwork/metaport": "^0.0.13",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

7. The page will not render and the console shows a variety of minified react errors such as: ```Uncaught Error: Minified React error #299; visit https://reactjs.org/docs/error-decoder.html?invariant=299 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at t.createRoot (index.js:2:1)
    at new t (index.js:152:1)
    at ./src/App.js (App.js:3:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.js (App.js:21:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1```

That link back to the initialization of the ```new Metaport``` call.

**Expected behavior**
The expected behavior should be that the app and widget render with no errors thrown on initialization.

**Screenshots**
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20197130/187776847-5b7566e1-7ace-4b65-9243-9de460f3e43f.png">

Tested on both up to date Brave & Chrome.

**Additional context**
As there are no other dependencies involved, I am not sure if there is anything within React that can fix this, but I will research and post any updates. I have tried various configurations on initialization, the SSR import, etc and nothing has worked so far.

**Comment by TheGreatAxios** [comment]
Update

```<div id="metaport"></div>``` needs to go in the index.html file. I had tried that previously and restarted the app and it did not work, however, I tried again and placed it above the ```<div id="root"></div>``` in react and it worked this time. 

Working code:

```<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />
    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
    <!--
      manifest.json provides metadata used when your web app is installed on a
      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    -->
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    <!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.

      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    -->
    <title>React App</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="metaport"></div>
    <div id="root"></div>
    <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm start` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->
  </body>
</html>
```
